---
name: eliud_pkg_fundamentals_model
description: eliud_pkg_feed is a package to provide fundamental gui components to
  your eliud app. More info at https://eliud.io
homepage: https://eliud.io
repository: https://github.com/eliudio/eliud_pkg_fundamentals
version: 1.0.0
environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.0.0'
dependencies:
  bloc: ^8.1.2
  cloud_firestore: ^4.12.2
  collection: ^1.17.2
  eliud_core:
    path: ../eliud_core
  eliud_core_helpers:
    path: ../eliud_core_helpers
  eliud_core_model:
    path: ../eliud_core_model
  eliud_pkg_medium:
    path: ../eliud_pkg_medium
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  flutter_markdown: ^0.6.18+2
  getwidget: ^4.0.0
  meta: ^1.9.1
  photo_view: ^0.14.0
  transparent_image: ^2.0.1
  flutter:
    sdk: flutter
dev_dependencies:
  build_runner: ^2.4.6
  eliud_generator:
    path: ../eliud_generator
  lints: ^3.0.0
flutter:
  uses-material-design: true
platforms:
  android: null
  ios: null
  web: null
